name: uerto
description: Uerto will be the new standard for social activities outside your home.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  built_value: ^8.4.3
  built_collection: ^5.1.1
  http: ^0.13.5
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1
  freezed_annotation: ^2.2.0
  flutter_appauth: ^4.2.1
  flutter_secure_storage: ^8.0.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  built_value_generator: ^8.4.3
  freezed: ^2.3.2
  flutter_lints: ^2.0.1


dependency_overrides:
  rxdart: ^0.27.7
  meta: ^1.9.0
  analyzer: ^5.2.0

flutter:
  uses-material-design: true

# [fonts]

# [assets]