name: uerto
description: Uerto will be the new standard for social activities outside your home.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_value: ^8.5.0
  built_collection: ^5.1.1
  http: ^0.13.6
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1
  freezed_annotation: ^2.2.0
  flutter_appauth: ^5.0.0
  flutter_secure_storage: ^8.0.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  google_maps_flutter: ^2.2.6
  google_static_maps_controller: ^1.0.0
  geolocator: ^9.0.2
  dart_geohash: ^2.0.2
  flutter_local_notifications: ^14.0.0+1
  flutter_datetime_picker: ^1.5.1
  timezone: ^0.9.2

  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  flutter_polygon: ^0.3.0+2
  dotted_line: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  built_value_generator: ^8.5.0
  freezed: ^2.3.3
  flutter_lints: ^2.0.1


dependency_overrides:
  rxdart: ^0.27.7
  meta: ^1.9.1
  analyzer: ^5.12.0

flutter:
  uses-material-design: true

# [fonts]

# [assets]
  assets:
    - assets/images/logo-short.png
    - assets/images/logo-big.png
    - assets/images/image-signs.png