// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzEElzedwILPIL_YDtHlKOWWDdOpUAm2A',
    appId: '1:836039419493:web:b0b57531a719d567f6488c',
    messagingSenderId: '836039419493',
    projectId: 'uerto-287508',
    authDomain: 'uerto-287508.firebaseapp.com',
    storageBucket: 'uerto-287508.appspot.com',
    measurementId: 'G-JBLKHN1ELW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVwYYqzfyU0lnPhH9Mf5yhkl35ksQKBM',
    appId: '1:836039419493:android:94ba62f810dc10b9f6488c',
    messagingSenderId: '836039419493',
    projectId: 'uerto-287508',
    storageBucket: 'uerto-287508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy44F4NEHebeydDUbxtuZ0kq3_ggGOdhg',
    appId: '1:836039419493:ios:e8ba65fd6a0a9123f6488c',
    messagingSenderId: '836039419493',
    projectId: 'uerto-287508',
    storageBucket: 'uerto-287508.appspot.com',
    iosClientId: '836039419493-uispplgm1p7tg96rkug71b4jd1oh00hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uerto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy44F4NEHebeydDUbxtuZ0kq3_ggGOdhg',
    appId: '1:836039419493:ios:e8ba65fd6a0a9123f6488c',
    messagingSenderId: '836039419493',
    projectId: 'uerto-287508',
    storageBucket: 'uerto-287508.appspot.com',
    iosClientId: '836039419493-uispplgm1p7tg96rkug71b4jd1oh00hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uerto',
  );
}
